2022-09-28 14:50:01,609 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': True} on 1 hosts
2022-09-28 14:50:01,995 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/asn1.py", line 45, in deploy_config
    config_rendered = get_api()
  File "/Users/rubendedman/PycharmProjects/bgp-peering/asn1.py", line 15, in get_api
    loader=PackageLoader("asn"),
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/jinja2/loaders.py", line 291, in __init__
    import_module(package_name)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'asn'

2022-09-28 14:50:14,548 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': False} on 1 hosts
2022-09-28 14:50:14,549 -  nornir.core -     INFO -        run() - Running task 'task_1' with args {'number': 2} on 1 hosts
2022-09-28 14:50:44,966 -  nornir.core -     INFO -        run() - Running task 'send_command' with args {'command': 'show ntp status'} on 1 hosts
2022-09-28 15:04:31,123 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': True} on 1 hosts
2022-09-28 15:04:31,431 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/asn1.py", line 45, in deploy_config
    config_rendered = get_api()
  File "/Users/rubendedman/PycharmProjects/bgp-peering/asn1.py", line 20, in get_api
    template = env.get_template("config.j2")
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 955, in _load_template
    raise TypeError("no loader for this environment specified")
TypeError: no loader for this environment specified

2022-09-28 15:07:48,773 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': False} on 1 hosts
2022-09-28 15:07:48,777 -  nornir.core -     INFO -        run() - Running task 'task_1' with args {'number': 2} on 1 hosts
2022-09-28 15:53:37,065 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': True} on 1 hosts
2022-09-28 15:53:37,402 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "templates/config.j2", line 3, in top-level template code
    neighbor {{ neighbor.ip }} description {{ neighbor.name }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'ip'

2022-09-28 15:53:37,403 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/asn2.py", line 22, in deploy_config
    result_jinja2 = task.run(task=template_file, path="templates", template="config.j2", bgp=data)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2022-09-28 15:54:08,571 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': False} on 1 hosts
2022-09-28 15:57:10,490 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': True} on 1 hosts
2022-09-28 15:57:10,860 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/rubendedman/PycharmProjects/bgp-peering/.venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/rubendedman/PycharmProjects/bgp-peering/asn2.py", line 27, in deploy_config
    configuration=config_rendered,
NameError: name 'config_rendered' is not defined

2022-09-28 15:57:23,183 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {'dry_run': False} on 1 hosts
